# Generated by Django 4.0.2 on 2022-02-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_choice', to='webapp.choice', verbose_name='Вариант')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_poll', to='webapp.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answer',
            },
        ),
    ]
